config/routes.rb
Rails.application.routes.draw do
  resources :variants
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :variants, inverse_of: :product
  accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.variants.build

    # 3.times do
    #   @product.variants.build
    # end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price,
                                      variants_attributes: [:id, :name, :price, :_destroy ])
    end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant, notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url, notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name = nil, f = nil, association = nil, options = nil, html_options = nil, &block)
    # If a block is provided there is no name attribute and the arguments are
    # shifted with one position to the left. This re-assigns those values.
    f, association, options, html_options = name, f, association, options if block_given?

    options = {} if options.nil?
    html_options = {} if html_options.nil?

    if options.include? :locals
      locals = options[:locals]
    else
      locals = { }
    end

    if options.include? :partial
      partial = options[:partial]
    else
      partial = association.to_s.singularize + '_fields'
    end

    # Render the form fields from a file with the association name provided
    new_object = f.object.class.reflect_on_association(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(partial, locals.merge!( f: builder))
    end

    # The rendered fields are sent with the link within the data-form-prepend attr
    html_options['data-form-prepend'] = raw CGI::escapeHTML( fields )
    html_options['href'] = '#'

    content_tag(:a, name, html_options, &block)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CocoonSample
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    = yield

app/views/products/_form.html.slim
= form_with(model: product, local: true) do |f|
  - if product.errors.any?
    #error_explanation
      h2
        = pluralize(product.errors.count, "error")
        |  prohibited this product from being saved:
      ul
        - product.errors.full_messages.each do |message|
          li
            = message


  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.number_field :price
  #variants
    = f.fields_for :variants do |variant|
      = render 'variant_fields', f: variant
    .links
      = link_to_add_association 'add task', f, :variants, id: 'add-link'
  .actions
    = f.submit

app/views/products/_variant_fields.slim
.nested-fields
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  = link_to_remove_association "remove variant", f

app/views/products/edit.html.slim
h1
  | Editing Product
= render 'form', product: @product
= link_to 'Show', @product
|  | 
= link_to 'Back', products_path

app/views/products/index.html.slim
p#notice
  = notice
h1
  | Products
table
  thead
    tr
      th
        | Name
      th
        | Price
      th[colspan="3"]
  tbody
    - @products.each do |product|
      tr
        td
          = product.name
        td
          = product.price
        td
          = link_to 'Show', product
        td
          = link_to 'Edit', edit_product_path(product)
        td
          = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1
  | New Product
= render 'form', product: @product
= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @product.name
p
  strong
    | Price:
  = @product.price
= link_to 'Edit', edit_product_path(@product)
|  | 
= link_to 'Back', products_path

app/views/variants/_form.html.slim
= form_with(model: variant, local: true) do |form|
  - if variant.errors.any?
    #error_explanation
      h2
        = pluralize(variant.errors.count, "error")
        |  prohibited this variant from being saved:
      ul
        - variant.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :price
    = form.number_field :price
  .actions
    = form.submit

app/views/variants/edit.html.slim
h1
  | Editing Variant
= render 'form', variant: @variant
= link_to 'Show', @variant
|  | 
= link_to 'Back', variants_path

app/views/variants/index.html.slim
p#notice
  = notice
h1
  | Variants
table
  thead
    tr
      th
        | Name
      th
        | Price
      th[colspan="3"]
  tbody
    - @variants.each do |variant|
      tr
        td
          = variant.name
        td
          = variant.price
        td
          = link_to 'Show', variant
        td
          = link_to 'Edit', edit_variant_path(variant)
        td
          = link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Variant', new_variant_path

app/views/variants/new.html.slim
h1
  | New Variant
= render 'form', variant: @variant
= link_to 'Back', variants_path

app/views/variants/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @variant.name
p
  strong
    | Price:
  = @variant.price
= link_to 'Edit', edit_variant_path(@variant)
|  | 
= link_to 'Back', variants_path